### ISSUE TITLE
Missing E2E Documentation 

### ISSUE THREAD

**Issue by dmedinag** [ymatsiuk/awsvpnclient#1]
Hi! first off, thanks a lot for the effort on this flake. I understand the README provides info on how to configure the flake so that the `awsvpnclient` derivation is available for me, but I fail to understand how to actually use it.

Would you be happy to illustrate how to use my cvpn-endpoint-<id>.ovpn file to connect to the vpn step by step?

Sorry for the inconvenience, and thanks again for the great work.

**Comment by ymatsiuk** [comment]
I updated the readme, let me know if you have other questions 🙂 
Thanks @dmedinag 👍🏻
