### ISSUE TITLE
patch failing

### ISSUE THREAD

**Issue by DanBiscotti** [ymatsiuk/awsvpnclient#8]
Hi, apologies if this is something I'm doing wrong, still quite new to nix and flakes.
I tried to add this to my system, but it seems to be failing with the following:
```
Hunk #2 FAILED at 2581.
1 out of 2 hunks FAILED -- saving rejects to file src/openvpn/manage.c.rej
patching file src/openvpn/manage.h
patching file src/openvpn/misc.h
Hunk #1 succeeded at 72 (offset 3 lines).
patching file src/openvpn/options.h
patching file src/openvpn/ssl.c
Hunk #1 succeeded at 2146 (offset 36 lines).
Hunk #2 succeeded at 2161 (offset 36 lines).
Hunk #3 succeeded at 2438 (offset 35 lines).
```
I cloned the repo and ran `nix build .` and got the same thing

**Comment by ymatsiuk** [comment]
Hey, :wave: it seems like you're running an older version of NixOS. This flake is not hermetic (doesn't pin the version of openvpn) and is actually meant for people who runs unstable (as myself).
This should fix your build:
```
    inputs.awsvpnclient.inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
```
or you could pin awsvpnclient:
```
    inputs.awsvpnclient.url = "github:ymatsiuk/awsvpnclient/7228bce80b664ceaa402105629355692cb71a28d";
```

Multiple options available there :wink: 
Let me know if that works!

**Comment by DanBiscotti** [comment]
That did fix it. Thanks for your help!
